import type { Metadata } from "next";
import Navbar from "@/Components/Navbar";
import { Geist, Geist_Mono } from "next/font/google";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
} from "@clerk/nextjs";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <div className="flex">
            {/* Show Navbar only if user is signed in - hidden on mobile/tablet, visible on lg screens */}
            <SignedIn>
              <div className="hidden lg:block">
                <Navbar />
              </div>
            </SignedIn>

            {/* Main content */}
            <main className="flex-1 w-full">
              {children}
            </main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
